### ISSUE TITLE
Mudlet 3.12 - StartAll() causing a syntax error

### ISSUE THREAD

**Issue by bduza** [demonnic/animatedtimers#8]
All testing done with the sample code cut and pasted, no changes done. (the 'Test2' timer)

1. Create the timer using the same code. There is a 10 second time the full width of my screen ticking away
2. Let it run out and disappear.

Send the command `demonnic.anitimer:StartAll()` by entering into a script object and clicking 'save' with the mouse. Script editor reports 'Lua syntax error' and 'attempt to call method 'StartAll' (a nil value)

**Comment by demonnic** [comment]
lua is case sensitive. It's demonnic.anitimer:startAll() not StartAll.
